spring.application.name=ubrs_backend
server.port=${PORT:7700}

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/ubrsDB}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:123}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CORS Configuration
# ===============================
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3300}

# ===============================
# Mail Configuration
# ===============================
#spring.mail.host=${MAIL_HOST:smtp.gmail.com}
#spring.mail.port=${MAIL_PORT:587}
#spring.mail.port=${MAIL_PORT:443}
#spring.mail.username=${MAIL_USERNAME:schoolfeeding.info@gmail.com}
#spring.mail.password=${MAIL_PASSWORD:vghk tmff cbpd meiy}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true



# ===============================
# Mailjet Configuration
# ===============================
mailjet.api-key=${MAILJET_API_KEY:eaf78ea3896a73441c8cfdda674ff4e3}
mailjet.secret-key=${MAILJET_SECRET_KEY:b7b5aaf682504543bed3cf02dc3741f3}
mailjet.from-email=${MAILJET_FROM_EMAIL:dujohnson777@gmail.com}
mailjet.from-name=${MAILJET_FROM_NAME:UBRS}