spring.application.name=ubrs_backend
server.port=7700

spring.datasource.url=jdbc:postgresql://localhost:5432/ubrsDB
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update



# ===============================
# PostgreSQL / Neon Database
# ===============================
#spring.datasource.url=jdbc:postgresql://ep-super-thunder-a531bauq-pooler.us-east-2.aws.neon.tech/ubrsDB?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_mguM3XkByn8A
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=schoolfeeding.info@gmail.com
spring.mail.password=vghk tmff cbpd meiy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
