import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface PdfOptions {
  title: string;
  reportPeriod: string;
  preparedBy: string;
  headers: string[][];
  body: (string | number)[][];
}

export const generateReportPdf = (options: PdfOptions) => {
  const { title, reportPeriod, preparedBy, headers, body } = options;
  const doc = new jsPDF();

  const logoUrl = "/assets/logo.png";
  
  // Format dates
  const today = new Date();
  const dateStr = today.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'long',
    year: 'numeric'
  });

  const generateDoc = (imgData?: string) => {
    // 1. Header Area
    if (imgData) {
      doc.addImage(imgData, "PNG", 14, 10, 25, 25);
    }
    
    // Header Texts (Left)
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 60, 110);
    doc.text("REPUBLIC OF RWANDA", 14, 42);
    doc.text("MINISTRY OF EDUCATION (MINEDUC)", 14, 48);
    doc.text("UMWANA BRIGHT ACADEMY", 14, 54);

    // Header Texts (Right)
    doc.text("P.O. Box 622 Kigali City", 196, 20, { align: "right" });

    // Top Horizontal Line
    doc.setDrawColor(30, 60, 110);
    doc.setLineWidth(0.5);
    doc.line(14, 60, 196, 60);

    // Report Details Section
    doc.setFont("helvetica", "bold");
    doc.text("REPORT DETAILS", 14, 68);

    // Orange Line
    doc.setDrawColor(230, 120, 50);
    doc.line(14, 72, 196, 72);

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Report Period:", 14, 82);
    doc.setFont("helvetica", "normal");
    doc.text(reportPeriod, 45, 82);

    doc.setFont("helvetica", "bold");
    doc.text("Prepared By :", 14, 89);
    doc.setFont("helvetica", "normal");
    doc.text(preparedBy, 45, 89);

    doc.setFont("helvetica", "bold");
    doc.text("Date Generated:", 14, 96);
    doc.setFont("helvetica", "normal");
    doc.text(dateStr, 45, 96);

    // Green Line
    doc.setDrawColor(50, 150, 80);
    doc.line(14, 104, 196, 104);

    // Report Title
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(30, 60, 110);
    doc.text(title, 105, 118, { align: "center" });

    // 2. Table
    autoTable(doc, {
      startY: 125,
      head: headers,
      body: body,
      theme: "grid",
      headStyles: {
        fillColor: [240, 240, 240],
        textColor: [0, 0, 0],
        fontStyle: "bold",
        lineWidth: 0.1,
        lineColor: [200, 200, 200],
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
        textColor: [50, 50, 50],
        lineColor: [200, 200, 200],
        lineWidth: 0.1,
      },
      alternateRowStyles: {
        fillColor: [255, 255, 255],
      },
      margin: { top: 20, right: 14, bottom: 40, left: 14 },
    });

    // 3. Footer area
    // Use the final Y position from autotable
    const finalY = (doc as any).lastAutoTable.finalY || 125;
    
    // Check if we need a new page for footer
    let footerY = finalY + 30;
    if (footerY > 260) {
      doc.addPage();
      footerY = 30;
    }

    doc.setFontSize(10);
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("Prepared By:", 14, footerY);
    doc.setFont("helvetica", "normal");
    doc.text(preparedBy, 45, footerY);

    doc.setFont("helvetica", "bold");
    doc.text("Signature:", 14, footerY + 10);
    doc.line(45, footerY + 10, 100, footerY + 10);

    doc.setFont("helvetica", "bold");
    doc.text("Date:", 14, footerY + 20);
    doc.setFont("helvetica", "normal");
    doc.text(dateStr, 45, footerY + 20);

    // Page numbers and system branding
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(9);
      doc.setFont("helvetica", "italic");
      doc.setTextColor(150, 150, 150);
      doc.text("Generated By Ubrs System", 105, 290, { align: "center" });
    }

    doc.save(`${title.toLowerCase().replace(/\s+/g, '_')}_${dateStr.replace(/\s+/g, '_')}.pdf`);
  };

  // Convert image to base64 to ensure it loads synchronously in the PDF
  const img = new Image();
  img.src = logoUrl;
  img.onload = () => {
    const canvas = document.createElement("canvas");
    canvas.width = img.width;
    canvas.height = img.height;
    const ctx = canvas.getContext("2d");
    if (ctx) {
      ctx.drawImage(img, 0, 0);
      const dataUrl = canvas.toDataURL("image/png");
      generateDoc(dataUrl);
    } else {
      generateDoc(); // fallback if canvas fails
    }
  };
  img.onerror = () => {
    generateDoc(); // generate without image if it fails to load
  };
};
